name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # FORÇA NODE 22 GLOBAL
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      # LIMPA INSTALAÇÃO E GARANTE NODE CERTO
      - name: Clean install
        run: |
          node -v
          npm -v
          npm install

      # BUILD ANGULAR (FORÇADO)
      - name: Build Angular
        run: npx ng build --configuration production

      - run: npx cap add android || true
      - run: npx cap sync android

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build APK
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug

      - uses: actions/upload-artifact@v4
        with:
          name: apk
          path: android/app/build/outputs/apk/debug/app-debug.apk